PUT http://localhost:8080/recipe/0
Content-Type: application/json

###
PUT http://localhost:8080/ingredients/0
Content-Type: application/json

{
  "nameIngredient": "Консервированная фасоль",
  "count": 400,
  "measureUnit": "г"
}

###
GET http://localhost:8080/ingredients/1

###
POST http://localhost:8080/ingredients
Content-Type: application/json

{
  "nameIngredient": "Специи",
  "count": 1,
  "measureUnit": "щепотка"
}

###
GET http://localhost:8080/recipe/0

###
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "name": "Салат из красной фасоли с творожным сыром, красным луком и сезонным салатом",
  "preparingTime": 7,
  "measureUnit": "мин.",
  "ingredients": [
    {
      "nameIngredient": "Специи",
      "count": 1,
      "measureUnit": "щепотка"
    },
    {
      "nameIngredient": "Консервированная фасоль",
      "count": 400,
      "measureUnit": "г"
    },
    {
      "nameIngredient": "Лимон",
      "count": 1,
      "measureUnit": "шт."
    },
    {
      "nameIngredient": "Чеснок",
      "count": 2,
      "measureUnit": "зубчик"
    },
    {
      "nameIngredient": "Оливковое масло",
      "count": 50,
      "measureUnit": "мл"
    },
    {
      "nameIngredient": "Рукола",
      "count": 100,
      "measureUnit": "г"
    },
    {
      "nameIngredient": "Творожный сыр",
      "count": 200,
      "measureUnit": "г"
    },
    {
      "nameIngredient": "Чеснок",
      "count": 50,
      "measureUnit": "г"
    }
  ],
  "steps": [
    "Открыть две банки красной фасоли в собственном соку, слить сок и промыть фасоль холодной водой.",
    "Готовую фасоль смешать с мелко нарубленным красным луком, зеленью, давленым чесноком, оливковыммаслом, лимонным соком и творожным сыром.",
    "Посолить, поперчить, дать продуктам две минуты притереться друг к другу и подавать к столу."
  ]
}

###
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "name": "Чечевичный суп с мятой",
  "preparingTime": 30,
  "measureUnit": "мин.",
  "ingredients": [
    {
      "nameIngredient": "Красная чечевица",
      "count": 150,
      "measureUnit": "г."
    },
    {
      "nameIngredient": "Репчатый лук",
      "count": 1,
      "measureUnit": "головка"
    },
    {
      "nameIngredient": "Морковь",
      "count": 1,
      "measureUnit": "шт."
    },
    {
      "nameIngredient": "Подсолнечное масло",
      "count": 30,
      "measureUnit": "мл."
    },
    {
      "nameIngredient": "Сливочное масло",
      "count": 15,
      "measureUnit": "г"
    },
    {
      "nameIngredient": "Пшеничная мука",
      "count": 30,
      "measureUnit": "г"
    },
    {
      "nameIngredient": "Сливки 33%",
      "count": 50,
      "measureUnit": "мл."
    },
    {
      "nameIngredient": "Специи",
      "count": 1,
      "measureUnit": "щепотка"
    },
    {
      "nameIngredient": "Лимон",
      "count": 1,
      "measureUnit": "шт."
    },
    {
      "nameIngredient": "Мята",
      "count": 1,
      "measureUnit": "щепотка"
    }
  ],
  "steps": [
    "В небольшую кастрюлю налить литр воды и засыпать промытую чечевицу. Поставить кастрюлю на среднийогонь",
    "Натереть небольшую морковь на крупной терке, мелко нарезать лук. Как только чечевица начнет кипеть,надо убавить огонь, а затем долить еще 200 мл воды или бульона. Варить еще десять минут",
    "Разогреть широкую плоскую сковороду, добавить туда подсолнечное и сливочное масло. Обжарить лук иморковь.",
    "Добавить обжаренные овощи в кастрюлю, влить сливки. Взбить суп ручным блендером, чтобы онпревратился в густое пюре. Суп можно подавать к столу."
  ]
}

###
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "name": "Салат с креветками и кунжутом",
  "preparingTime": 20,
  "measureUnit": "мин.",
  "ingredients": [
    {
      "nameIngredient": "Помидоры",
      "count": 3,
      "measureUnit": "шт."
    },
    {
      "nameIngredient": "Королевские креветки",
      "count": 300,
      "measureUnit": "г"
    },
    {
      "nameIngredient": "Зеленый салат",
      "count": 1,
      "measureUnit": "пучок"
    },
    {
      "nameIngredient": "Огурцы",
      "count": 2,
      "measureUnit": "шт."
    },
    {
      "nameIngredient": "Специи",
      "count": 1,
      "measureUnit": "щепотка"
    },
    {
      "nameIngredient": "Майонез",
      "count": 1,
      "measureUnit": "ст. л."
    },
    {
      "nameIngredient": "Кунжутные семечки",
      "count": 3,
      "measureUnit": "ст. л."
    }
  ],
  "steps": [
    "Порезать овощи крупно, салат порвать на куски.",
    "Довести до кипения сильно соленую воду и добавить креветки. После кипения варить 5 минут.",
    "Очистить креветки от панциря.",
    "Смешать овощи и креветки.",
    "Посыпать кунжутными семечками и заправить майонезом."
  ]
}

###
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "name": "Творожные пончики в сахарной пудре",
  "preparingTime": 40,
  "measureUnit": "мин.",
  "ingredients": [
    {
      "nameIngredient": "Творог",
      "count": 250,
      "measureUnit": "г."
    },
    {
      "nameIngredient": "Куриное яйцо",
      "count": 3,
      "measureUnit": "шт."
    },
    {
      "nameIngredient": "Пшеничная мука",
      "count": 8,
      "measureUnit": "ст. л."
    },
    {
      "nameIngredient": "Сахар/Соль",
      "count": 1,
      "measureUnit": "щепотка"
    },
    {
      "nameIngredient": "Оливковое масло",
      "count": 1,
      "measureUnit": "ст. л."
    },
    {
      "nameIngredient": "Сода",
      "count": 1,
      "measureUnit": "ч. л."
    },
    {
      "nameIngredient": "Сахарная пудра с ванилью",
      "count": 1,
      "measureUnit": "щепотка"
    }
  ],
  "steps": [
    "В миске смешать творог, яйца, муку, сахар, соду и соль до однородной консистенции.",
    "В небольшом сотейнике оливковое масло хорошо разогреть.",
    "При помощи чайной ложки или руками скатать из теста шарики, каждый размером чуть меньше грецкого ореха.",
    "Бросить пончики в кипящее масло и жарить на небольшом огне, постоянно переворачивая шумовкой.",
    "Готовые пончики выложить на бумажное полотенце и оставить на одну-две минуты — чтобы оно впитало лишнее масло. Подавать пончики горячими, выложив на блюдо и посыпав сахарной пудрой, смешанной с ванилином."
  ]
}
